BOT_TOKEN: "8790173158:AAEBpoUx_8QHL0AHae7Xox1VEzcqdo9Ul2A"  # токен бота
CHANNEL_URL: "https://t.me/profit_wollstreet"  # Ссылка на канал
CHANNEL_ID: "-1003979747241"  # айди своего основного канала, начинается с -
VERIF_CHANNEL_ID: "-1003807106897"  # айди канала для отчётов, начинается с -
ADMIN_ID: 1352557466  # свой айди аккаунта, который будет админом в канале
support_url: "https://t.me/djjfnfjdjd" # тут ссылка на ваш телеграм аккаунт, как аккаунт поддержки
DATABASE_PATH: "database/user.db" # путь к базе данных, не трогай если не знаешь для чего
enabled_languages: #в таком же формате как ниже, укажите какие языки хотите видеть в боте, убедитесь что они есть в lang.yaml, если нет, добавьте, в таком же формате, как там
- ru
